version: '3'
services:
  backup:
    build: .
    env_file:
      - restic_volume_backup.env
    volumes:
      # Map in docker socket
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # Map in project source
      - .:/restic-volume-backup
