version: '3.7'

services:
  mariadb:
    image: mariadb:10
    labels:
      restic-compose-backup.mariadb: "true"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    networks:
      - global
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:

networks:
  global:
    external: true
